= REDHAWK Driver

The REDHAWK Driver asset encompasses several utility interfaces that give users convienent API access to REDHAWK via Java. The goal is to hide any CORBA interaction from  programmers so they can focus effort on writing the logic for their application. 

== Getting Started

If using maven, you can add the following xml to your project's current pom:

[source,xml]
----
	<groupId>redhawk</groupId>
	<artifactId>redhawk-driver</artifactId>
	<version>${version}</version>
----

Note: ${version} is version of the driver you want to use. 

If familiar with maven, and you are starting from scratch, you can use the redhawk-driver-bundle-archetype to generate your project structure by running this command:

----
mvn archetype:generate -DarchetypeGroupId=redhawk -DarchetypeArtifactId=redhawk-driver-bundle-archetype -DarchetypeVersion=1.0.0-SNAPSHOT
----

After running the command, you are prompted for the following information:

* groupId
* artifactId
* version
* package

After entering the necessary information, a template project is created that already has the REDHAWK Driver dependency setup and a simple main method in App.java that utilizes the REDHAWK Driver asset. 

If not using maven, you can add the .jar file to your project's build path or configure it with your project's build tool as needed. 

The following code examples may be helpful to developers getting started with the REDHAWK Driver. 


