= REDHAWK Driver

The REDHAWK Driver asset encompasses several utility interfaces that give users convienent API access to REDHAWK via Java. The goal is to hide any CORBA interaction from  programmers so they can focus effort on writing the logic for their application. 

== Getting Started

If using Maven, add the following to the dependency section of your project's pom:

[source,xml]
----
	<groupId>${project.groupId}</groupId>
	<artifactId>${project.artifactId}</artifactId>
	<version>${project.version}</version>
----

If familiar with Maven, and you are starting from scratch, you can use the `redhawk-driver-bundle-archetype` to generate your project structure by running this command:

----
mvn archetype:generate -DarchetypeGroupId=redhawk \
 -DarchetypeArtifactId=redhawk-driver-bundle-archetype \
 -DarchetypeVersion=1.0.0-SNAPSHOT
----

After running the command, you are prompted for the following information:

* `groupId`
* `artifactId`
* `version`
* `package`

After entering the necessary information, a template project is created that already has the REDHAWK Driver dependency in your pom and a simple main method in `App.java` that utilizes the REDHAWK Driver asset. 

[IMPORTANT]
====
We're in the process of making the REDHAWK Enterprise Integration dependencies available on a public maven repository. Until then you will need to follow the `Build From Source` instructions in the readme included with this projects source code to add the redhawk-driver to your local maven repository. 

Alternatively, when you installed the redhawk-enterprise-integration tgz/rpm the karaf distribution came with a system maven repository. Add this system maven repository to your settings.xml file. Here is an example profile you could add to your settings.

[source,xml]
----
<profile>
	<id>rei</id>
	<repositories>
		<repository>
			<id>dev-rei</id>
			<name>Development REI</name>
			<url>file://<!-- path to ${karaf.base}/system repo --></url>
​          <releases>
​            <enabled>true</enabled>
​            <updatePolicy>never</updatePolicy>
​          </releases>
​          <snapshots>
​            <enabled>false</enabled>
​            <updatePolicy>never</updatePolicy>
​          </snapshots>			
		</repository>
	</repositories>
</profile>
----

_If using profile make sure you add to your active profiles_
====

If not using Maven, you can add the .jar file to your project's build path or configure it with your project's build tool as needed. 

The following code examples may be helpful to developers getting started with the REDHAWK Driver. 

[NOTE]
====
All code examples are coming directly from actual REDHAWK Driver Integration Tests. For the full imports needed for the code examples and more details refer to the source files where the examples(snippets) are taken from. The source files for all test relevant to the REDHAWK Driver can be found in the `src/test/java` directory for the REDHAWK Driver module.
====