= REDHAWK Driver

The REDHAWK Driver asset encompasses several utility interfaces that give users convienent API access to REDHAWK via Java. The goal is to hide any CORBA interaction from  programmers so they can focus effort on writing the logic for their application. 

== Getting Started

If using Maven, add the following to the dependency section of your project's pom:

[source,xml]
----
	<groupId>${project.groupId}</groupId>
	<artifactId>${project.artifactId}</artifactId>
	<version>${project.version}</version>
----

If familiar with Maven, and you are starting from scratch, you can use the `redhawk-driver-bundle-archetype` to generate your project structure by running this command:

----
mvn archetype:generate -DarchetypeGroupId=redhawk \
 -DarchetypeArtifactId=redhawk-driver-bundle-archetype \
 -DarchetypeVersion=1.0.0-SNAPSHOT
----

After running the command, you are prompted for the following information:

* `groupId`
* `artifactId`
* `version`
* `package`

After entering the necessary information, a template project is created that already has the REDHAWK Driver dependency setup and a simple main method in `App.java` that utilizes the REDHAWK Driver asset. 

If not using Maven, you can add the .jar file to your project's build path or configure it with your project's build tool as needed. 

The following code examples may be helpful to developers getting started with the REDHAWK Driver. 

_Note: All code examples are coming directly from actual Integration Tests. For the full imports needed for the code examples and more details refer to the source files where the examples(snippets) are taken from_


