= REDHAWK Connector

== Overview

Using the REDAHWK Connector to create a Redhawk Connection results in the following:

* A REDHAWK Driver instance is registered in the OSGi Service Registry.
* A custom Camel Component is configured.
* A Websocket service is available for the connection.
* A REST Endpoint is available for the connection.

== Configuring REDHAWK Connector

.Configuration Table
|===

|*Name* | *Key* | *Required* | *Default* | *Description*

| Connection Name
| connectionName
| Yes
| null
| Unique name used to identify this connection. 

| Server Name
| host
| Yes
| localhost
| Hostname or IP Address of the CORBA Naming Service.

| Port
| port
| Yes
| 2809
| Port where the CORBA naming service is listening.

| Domain Manager Location
| domainManager
| No
| null
| Optional name of the REDHAWK Domain Manager(as found in the CORBA Naming Service). 

| Device Manager Name
| deviceManagerName
| No
| null
| The name of the Device Manager to register with REDHAWK.

| Device Manager File System
| deviceManagerFileSystemRoot
| No
| null
| The filesystem root of the Device Manager. 

|===

== Creating a REDHAWK Connector Configuration

To create a REDHAWK Connector configuration through the console for your Karaf instance: 

* Open a browser to '/system/console/configMgr' of your running Karaf instance. 
Note: For example, '127.0.0.1:8181/system/console/configMgr'.

To create a REDHAWK Connector configuration using a file:

* Add a configuration for REDHAWK by dropping a file beginning with this prefix: 'redhawk.datasource.factory' and append a unique string (i.e., myConfig.cfg) file into the etc directory of your Karaf install.

Example config file:
----
connectionName=localRH
port=2809
host=localhost
domainManager=REDHAWK_DEV
----

== Using Connection in blueprint

To inject the Redhawk Driver instance into your application, add the following lines in your blueprint.xml file:

[source,xml]
----
<reference id="myRedhawkService" interface="redhawk.Redhawk" filter="(connectionName='insert connection name'"/>)

<bean id="myApplicationBean" class="com.example.MyApplicationBeanImpl">
	<property name="redhawk" ref="myRedhawkService" />
</bean>
----
