= REDHAWK Driver 

== Testing

To run integration tests follow instructions in above readme for testing. 

To run integration tests with Jacorb run the following command:

----
mvn clean install -P localIT -Djacorb=true
----

== Docs 

To generate the docs for redhawk-driver: 

----
mvn -P docs generate-resources
----

This generates documentation for you at this location 'redhawk-rest/target/docs/' . In that location is a pdf and html file with the documentation generated for this project. 

Javadocs are generated as an attached artifact as part of the default build for this asset. If you'd like to only generate javadocs you can do that by running the following command:

----
mvn javadoc:javadoc
----

The output of this command will be in: 

----
${project.build.dir}/site/apidocs/index.html
----

You can open this up in your browser by simply putting the file url in your browser of choice. 

=== Trouble Shooting

If you run into this error building the docs

----
[ERROR] Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:1.5.3:process-asciidoc (output-pdf) on project redhawk-rest: Execution output-pdf of goal org.asciidoctor:asciidoctor-maven-plugin:1.5.3:process-asciidoc failed: org.jruby.exceptions.RaiseException: (NotImplementedError) fstat unimplemented unsupported or native support failed to load -> [Help 1]
----

You'll need to specify the java.io.tmpdir with your maven command. So your command will end up looking like this:

----
mvn -P -Djava.io.tmpdir=./ -P jaxb-generation,docs generate-resources
----

////
## Base Karaf Usage ##
***

	feature:repo-add mvn:redhawk/redhawk-feature/${project.version}/xml/features
	feature:install redbus-redhawk-driver
////

