#GitLab CI File for REDHAWK Integration Asset
#Tutuorial on using GitLab CI: https://docs.gitlab.com/ce/ci/quick_start/README.html
#Docs on format of CI file: https://docs.gitlab.com/ce/ci/yaml/README.html
stages:
  - build
  - test-el6
  - test-el6-i386
  - test-el7
  - deploy

variables:
  enterprise_version: '2.1.0'
#  redhawk_version: '2.1-nightly'
.common: &common
  image: ${docker_registry}redbus/maven:3-jdk-8
  stage: build
  tags:
    - mvn-cache
  before_script:
    - mvn -P CFDependencies clean install -B -U
  after_script:
    - mkdir -p output
    - cp docs/target/asciidoc/html/index.html output/index.html #Docs artifacts
    - cp docs/target/asciidoc/pdf/index.pdf output/REDHAWK_Enterprise_v$enterprise_version.pdf
    - cp docs/target/rpm/redhawk-enterprise-integration-docs/RPMS/noarch/*.rpm output/ #RPM for installing REDHAWK Java Tools Docs in KARAF
    - cp dist/target/redhawk-enterprise-integration.tar.gz output/ #Tar of full distribution
    - cp dist/target/rpm/redhawk-enterprise-integration-dist/RPMS/noarch/*.rpm output/ #RPM for distribution
    - cp demo/demo-dist/target/rpm/redhawk-enterprise-integration-demo-dist/RPMS/noarch/*.rpm output/ #RPM for deploying demos
    - cp demo/demo-dist/target/redhawk-enterprise-integration-demo-dist.tar.gz output/ #tar for deploying demos
    - tar zcvf output.tar.gz output/
  artifacts:
    name: $CI_JOB_NAME
    paths:
      - output/index.html
      - output/*.pdf
      - output/*.rpm
      - output.tar.gz
    expire_in: 3 days

.deploy-common: &deploy-common
  image: centos:7
  stage: deploy
  dependencies: []
  script:
  - if [ -n "$jenkins_url" ]; then
      curl --insecure -X POST $jenkins_url/job/$jenkins_job/buildWithParameters?pipeline_id=$CI_PIPELINE_ID --user $jenkins_user:$jenkins_api_token;
    fi

build:
  <<: *common
  script:
    - mvn -Djava.io.tmpdir=./ deploy -P docs,jaxb-generation,default -B -U -Drelease=0.$CI_PIPELINE_ID
  only:
    - branches

build-release:
  <<: *common
  script:
    - mvn -Djava.io.tmpdir=./ clean install -P docs,jaxb-generation,default -B -U
  only:
    - tags

test-install:
  image: centos:7
  stage: test-el7
  script:
    - yum install -y `find output -name '*.rpm'`

test-el7-x86_64:
  image: ${docker_registry}utils/docker-compose:latest
  stage: test-el7
  tags:
    - mvn-cache
  dependencies: []
  variables:
    redhawk_version: 2.1-nightly
    dist: el7
    arch: x86_64
  script:
    - docker-compose up --force-recreate -d redhawk
    - docker-compose exec -T redhawk yum install -y redhawk-basic-components redhawk-basic-waveforms
    - docker-compose up --exit-code-from rei
    - find */target/failsafe-reports -name 'TEST*.xml' | tar cvf $CI_PROJECT_DIR/output.tar --files-from -
  after_script:
    - docker-compose down
  artifacts:
    name: $CI_JOB_NAME
    paths:
      - output.tar
    expire_in: 3 days

test-el6-x86_64:
  image: ${docker_registry}utils/docker-compose:latest
  stage: test-el6
  tags:
    - mvn-cache
  dependencies: []
  variables:
    redhawk_version: 2.1-nightly
    dist: el6
    arch: x86_64
  script:
    - docker-compose up --force-recreate -d redhawk
    - docker-compose exec -T redhawk yum install -y redhawk-basic-components redhawk-basic-waveforms
    - docker-compose up --exit-code-from rei
    - find */target/failsafe-reports -name 'TEST*.xml' | tar cvf $CI_PROJECT_DIR/output.tar --files-from -
  after_script:
    - docker-compose down
  artifacts:
    name: $CI_JOB_NAME
    paths:
      - output.tar
    expire_in: 3 days

test-el6-i386:
  image: ${docker_registry}utils/docker-compose:latest
  stage: test-el6-i386
  tags:
    - mvn-cache
  dependencies: []
  variables:
    redhawk_version: 2.1-nightly
    dist: el6
    arch: i686
  script:
    - docker-compose up --force-recreate -d redhawk
    - docker-compose exec -T redhawk yum install -y redhawk-basic-components redhawk-basic-waveforms
    - docker-compose up --exit-code-from rei
    - find */target/failsafe-reports -name 'TEST*.xml' | tar cvf $CI_PROJECT_DIR/output.tar --files-from -
  after_script:
    - docker-compose down
  artifacts:
    name: $CI_JOB_NAME
    paths:
      - output.tar
    expire_in: 3 days

#Trigger a Jenkins job to aggregate artifacts there
deploy:
  variables:
    jenkins_job: REDHAWK-enterprise-$CI_COMMIT_REF_NAME
  <<: *deploy-common
  only:
    - branches

deploy-release:
  variables:
    jenkins_job: $redhawk_version/job/REDHAWK-enterprise-$enterprise_version
  <<: *deploy-common
  only:
    - tags
