#GitLab CI File for REDHAWK Integration Asset
#Tutuorial on using GitLab CI: https://docs.gitlab.com/ce/ci/quick_start/README.html
#Docs on format of CI file: https://docs.gitlab.com/ce/ci/yaml/README.html
variables:
  DOCKER_REGISTRY_URL: ''
cache:
  key: "$CI_BUILD_REF_NAME"
  paths:
    - cache/maven.repository
build:
  image: ${DOCKER_REGISTRY_URL}redbus/maven:3-jdk-8
  script:
    - mvn -P CFDependencies clean install -B -U -Dmaven.repo.local=`pwd`/cache/maven.repository
    - mvn clean deploy -B -U -Dmaven.repo.local=`pwd`/cache/maven.repository
    - mvn -Djava.io.tmpdir=./ -P jaxb-generation,docs compile -B -U -Dmaven.repo.local=`pwd`/cache/maven.repository
  artifacts:
    paths:
    - docs/target/asciidoc/html/index.html #Website for REDHAWK Java Tools User Manual
    - docs/target/asciidoc/pdf/index.pdf #PDF for REDHAWK Java Tools User Manual
    - docs/target/rpm/redhawk-java-tools-docs/RPMS/noarch/*.rpm #RPM for installing REDHAWK Java Tools Docs in KARAF
    - dist/target/java-tools.tar.gz #Tar of full distribution
    - dist/target/rpm/redhawk-java-tools-dist/RPMS/noarch/*.rpm #RPM for distribution
    - demo/demo-dist/target/rpm/redhawk-demo-dist/RPMS/noarch/*.rpm #RPM for deploying demos
