#GitLab CI File for REDHAWK Integration Asset
#Tutuorial on using GitLab CI: https://docs.gitlab.com/ce/ci/quick_start/README.html
#Docs on format of CI file: https://docs.gitlab.com/ce/ci/yaml/README.html
cache:
  key: "$CI_BUILD_REF_NAME"
  untracked: true
variables:
  MAVEN_OPTS: -Dmaven.repo.local=/cache/maven.repository
build:
  image: redbusci/maven:3-jdk-8
  script:
    - mvn -P CFDependencies clean install -B -U
    - mvn -Djava.io.tmpdir=./ -P defaulti,jaxb-generation,docs clean deploy -B -U
  artifacts:
    paths:
    - redhawk-rest/target/docs/pdf/index.pdf
