#GitLab CI File for REDHAWK Integration Asset
#Tutuorial on using GitLab CI: https://docs.gitlab.com/ce/ci/quick_start/README.html
#Docs on format of CI file: https://docs.gitlab.com/ce/ci/yaml/README.html
cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - cache/maven.repository
build:
  image: ${DOCKER_REGISTRY_URL}redbus/maven:3-jdk-8
  script:
    - mvn -P CFDependencies clean install -B -U -Dmaven.repo.local=`pwd`/cache/maven.repository
    - mvn -Djava.io.tmpdir=./ deploy -P docs,jaxb-generation,default -B -U -Dmaven.repo.local=`pwd`/cache/maven.repository -Drelease=0.$CI_PIPELINE_ID
    - mkdir -p output
    - cp -r docs/target/asciidoc output/ #Docs artifacts
    - cp docs/target/rpm/redhawk-enterprise-integration-docs/RPMS/noarch/*.rpm output/ #RPM for installing REDHAWK Java Tools Docs in KARAF
    - cp dist/target/redhawk-enterprise-integration.tar.gz output/ #Tar of full distribution
    - cp dist/target/rpm/redhawk-enterprise-integration-dist/RPMS/noarch/*.rpm output/ #RPM for distribution
    - cp demo/demo-dist/target/rpm/redhawk-enterprise-integration-demo-dist/RPMS/noarch/*.rpm output/ #RPM for deploying demos
    - tar zcvf output.tar.gz output/
  artifacts:
    name: $CI_JOB_NAME
    paths:
      - output.tar.gz
    expire_in: 3 days

#Trigger a Jenkins job to aggregate artifacts there
deploy:
  image: centos:7
  stage: deploy
  dependencies: []
  script:
  - if [ -n "$jenkins_url" ]; then
      curl --insecure -X POST $jenkins_url/job/$jenkins_job/build --user $jenkins_user:$jenkins_api_token;
    fi
