version: '2'
services:
  redhawk:
    image: rei/redhawk:1.0
    container_name: redhawk_dev
#    volumes:
#      - sdrroot:/var/redhawk/sdr
  rei:
    image: rei/localit:1.0
    container_name: rei_maven
    command: /bin/bash
    tty: true
    volumes:
      - /data/mkwyche/.m2:/root/.m2:rw

#volumes:
#  sdrroot:
