version: '2'
services:
  redhawk:
    image: redhawk:2.0-nightly
    container_name: redhawk_dev
#    command: /bin/bash
#    tty: true
#    volumes:
#      - data-volume:/var/redhawk/sdr
  rei:
    image: rei/localit:latest
    container_name: rei_maven
    depends_on:
      - "redhawk"
    volumes:
      - /data/mkwyche/.m2:/root/.m2:rw
    command: /bin/bash
    tty: true
#    command: mvn test -Dtest=RedhawkDriverIT -DtestProps=/usr/local/workspace/enterprise/docker_test.properties
#    tty: true
#    volumes:
#      - /data/mkwyche/.m2:/root/.m2:rw

#TODO: Directory is shared but can't see waveforms etc...
#      - data-volume:/var/redhawk/sdr
#      - /data/mkwyche/.m2:/root/.m2:rw

#volumes:
#  data-volume: {}
