version: '2'
services:
  redhawk:
    image: ${docker_registry}redhawk/redhawk:${redhawk_version}-${dist}-${arch}
    container_name: redhawk
  rei:
    image: ${docker_registry}redbus/maven:3-jdk-8
    depends_on:
      - redhawk
    volumes:
      - .:/usr/src/app
      - ${m2cache}/repository:/root/.m2/repository:rw
    working_dir: /usr/src/app
    command: bash -c "mvn -P CFDependencies clean install -B -U && mvn clean install -pl redhawk-rest -P localIT -DfailIfNoTests=false -DtestProps=`pwd`/docker_test.properties"
