version: '2.1'
services:
  redhawk:
    image: ${docker_registry}redhawk/redhawk:${redhawk_version}-assets-${dist}-${arch}
    container_name: redhawk_${dist}_${arch}_${CI_JOB_ID}
  rei:
    image: ${docker_registry}redbus/maven:3-jdk-8
    depends_on:
      - redhawk
    volumes:
      - .:/usr/src/app
      - ${m2cache}/repository:/root/.m2/repository:rw
    working_dir: /usr/src/app
    #command: ${maven_command}
    command: bash -c "mvn -P CFDependencies clean install -B -U && mvn clean install -pl redhawk-driver -P localIT -Dtest=RedhawkUtilsIT#testProperyNamesToIdMap -DfailIfNoTests=false -DdomainHost=redhawk_${dist}_${arch}_${CI_JOB_ID} -DtestProps=`pwd`/docker_test.properties"
