version: '2'
services:
  redhawk:
    image: ${docker_registry}redhawk/redhawk:${redhawk_version}-${dist}-${arch}
    container_name: redhawk_${CI_JOB_ID}
  rei:
    image: ${docker_registry}redbus/maven:3-jdk-8
    depends_on:
      - redhawk_${CI_JOB_ID}
    volumes:
      - .:/usr/src/app
      - ${m2cache}/repository:/root/.m2/repository:rw
    working_dir: /usr/src/app
    command: bash -c "mvn clean install -PlocalIT -DfailIfNoTests=false -DdomainHost=redhawk_${CI_JOB_ID} -DtestProps=`pwd`/docker_test.properties"
