version: '2'
services:
  redhawk:
    image: redhawk:2.0-nightly
    container_name: redhawk_dev
  rei:
    image: rei/localit:latest
    container_name: rei_maven
    depends_on:
      - "redhawk"
    volumes:
      - /data/mkwyche/.m2:/root/.m2:rw

#If adding data-volume between container
#volumes:
#  data-volume: {}
