version: '2'
services:
  redhawk:
    image: ${docker_registry}redhawk/redhawk:${redhawk_version}-${dist}-${arch}
    container_name: redhawk_${dist}_${arch}_${CI_JOB_ID}
  rei:
    image: ${docker_registry}redbus/maven:3-jdk-8
    depends_on:
      - redhawk
    volumes:
      - .:/usr/src/app
      - ${m2cache}/repository:/root/.m2/repository:rw
    working_dir: /usr/src/app
    command: bash -c "mvn -P CFDependencies clean install -B -U && mvn -pl redhawk-camel test -Dtest=RedhawkEventChannelEndpointTestMT -DfailIfNoTests=false -DdomainHost=redhawk_${dist}_${arch}_${CI_JOB_ID} -DtestProps=`pwd`/docker_test.properties"
#    command: bash -c "mvn -P CFDependencies clean install -B -U && mvn clean install site -P localIT -DfailIfNoTests=false -DdomainHost=redhawk_${dist}_${arch}_${CI_JOB_ID} -DtestProps=`pwd`/docker_test.properties"
