= REI Integration Tests Prototype

* Maven REI source code will be in one container. REDHAWK will be in the other. 

* The container w/ Maven REI source will run the integration tests agains the container w/ REDHAWK_DEV

* Inside of gitlab-ci we could run docker-compose up --abort-on-container-exit . A bad exit code should be returned if the tests fail? 

*How to link this in w/ GitLab-CI????*
 
== Notes on how to get IT test running with docker

Need to mount host maven repo to make this run script faster: https://docs.docker.com/engine/tutorials/dockervolumes/#locate-a-volume

Stop downloading the world on build: 
* https://github.com/chanezon/docker-tips/blob/master/java-build-mount-maven-repo.mdi
* http://blog.flurdy.com/2014/11/dont-download-internet-share-maven-ivy-docker.html

Updating dir perms so you can see it:
* https://github.com/moby/moby/issues/14175

Example docker command: 
----
docker run -d -t -v /data/tmp/.m2:/root/.m2:rw rei/maven:1.0
----

Blah had to set TMP dir to get dockercompose working:
https://github.com/docker/compose/issues/1339
----
export TMP=[dir with exec perms]
----

docker-compose v. 3 requires docker 1.13 which isn't available in any centos repo yet. So downgraded to v. 2

Needed to set tty: https://stackoverflow.com/questions/37100358/docker-composer-exited-with-code-0

Aborting on container exit: https://stackoverflow.com/questions/33799885/how-to-stop-all-containers-when-one-container-stops-with-docker-compose
