= Redhawk Integration

////
* [Redhawk Driver](redhawk-driver/readme.md): Library that enables Java developer to interact with REDHAWK. Provides the ability to command & control your REDHAWK instance programatically.  
* [Redhawk Connector](redhawk-connector): Uses OSGi's Managed Service Factory interface to allow users to register pre-configured instances of REDHAWK connections into a KARAF container. 
* [Redhawk REST](redhawk-rest): Provides REST Service to command and control REDHAWK Instance
* [Redhawk Websocket](redhawk-websocket): Enables users to connect to a port of event channel and provide data back to a GUI using a websocket. 
* [Camel REDHAWK](camel-redhawk): Provides REDHAWK Camel Component. S 
* [Redhawk Feature](redhawk-featutre): Contains Feature for installing all of the above REDHAWK assets into base KARAF 
* [Redhawk Karaf Assembly](redhawk-karaf-assembly): Builds a custom KARAF distribution with a Redhawk Driver, Redhawk Connector, Redhawk Websocket, Redhawk REST and Camel REDHAWK pre-installed.  

////

== Building From Source 


The REHDAWK Integration assets depends on some dependencies that Core Framework builds:

* ossie
* BULKIOInterfaces
* FRONTENDInterfaces
* CFInterfaces

In order to make sure those dependencies are avaialbe for you when building from source. You must first run the profile:

----
mvn -PCFDependencies clean install 
----

Running that command will put the Core framework dependencies in your defined .m2 repository so the default build of all the artifacts will have all the dependencies it needs. You only need to run this command once. 

In order to build the artifacts that encompass Redhawk Java Tools from source. Run the following command:

----
mvn clean install
----

== Running Integration Tests

Currently the integration tests are run off a local install of REDHAWK. The domain is run locally and uses the following defaults:

* port: 2809
* domainName: REDHAWK_DEV

Once you have REDHAWK installed and a domain configured with the defaults listed above. You can run this command to get the integration tests to work:

	mvn -PlocalIT clean install 

This will be made more configurable in the future and will eventually also have an option to run off a docker image of REDHAWK. 

== Build Docs 

Each individual project has it's own readme defining how to build it's docs. If you'd like to build the full user manual. Run this profile: 

----
mvn -P jaxb-generation,docs compile
----

=== Trouble Shooting

If you run into this error building the docs

----
[ERROR] Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:1.5.3:process-asciidoc (output-pdf) on project redhawk-rest: Execution output-pdf of goal org.asciidoctor:asciidoctor-maven-plugin:1.5.3:process-asciidoc failed: org.jruby.exceptions.RaiseException: (NotImplementedError) fstat unimplemented unsupported or native support failed to load -> [Help 1]
----

You'll need to specify the java.io.tmpdir with your maven command. So your command will end up looking like this:

----
mvn -P -Djava.io.tmpdir=./ -P jaxb-generation,docs compile
----