= Redhawk Enterprise Integration

////
Release notes:

1. To release update the release number property in the parent pom. 

2. mvn -P CFDependencies,docs,default,jaxb-generation release:prepare -Darguments=-Djava.io.tmpdir=./

3. mvn release:perform -Darguments=-Djava.io.tmpdir=./
////

This repository provides a suite of assets for interacting with REDHAWK from a JRE. Below are the main assets and a brief description: 

* link:redhawk-driver/readme.adoc[REDHAWK Driver]: Provides simplified access to REDHAWK via standard Java interfaces. This Asset shields all interaction with the underlying REDHAWK Components and provides a simplified API for Java developers interacting with a REDHAWK Domain. The REDHAWK Driver can be leveraged as a standalone Java Archive (JAR) file.

* link:redhawk-connector/readme.adoc[REDHAWK OSGi Connecto]r: Implements OSGi’s Managed Service Factory interface to allow users to register pre-configured instances of REDHAWK connections into a Karaf container.

* link:redhawk-rest/readme.adoc[REDHAWK REST]: Provides a REST Service to command and control a REDHAWK instance.

* link:redhawk-websocket/readme.adoc[REDHAWK WebSocket]: Provides an HTML5-compliant WebSocket implementation that enables the ability to stream data from any REDHAWK BulkIO-enabled Port or Event Channel.

* link:redhawk-camel/readme.adoc[Camel REDHAWK]: Provides a Camel Component for interacting with a REDHAWK Domain. This Component can be connected with other Apache Camel Components as a data flow solution.

== Demo Assets

* link:camel-event-channel/README.md[Camel Event Channel Demo]

* link:demo/redhawk-webapp/README.md[REDHAWK Webapp Demo]

== Archetypes

* link:archetypes/redhawk-driver-bundle-archetype/readme.adoc[REDHAWK Driver Archetype]

== Building From Source 


The REHDAWK Enterprise Integration assets depends on some dependencies that Core Framework builds:

* ossie
* BULKIOInterfaces
* FRONTENDInterfaces
* CFInterfaces

In order to make sure those dependencies are avaialbe for you when building from source. You must first run the profile:

----
mvn -PCFDependencies clean install 
----

Running that command will put the Core framework dependencies in your defined .m2 repository so the default build of all the artifacts will have all the dependencies it needs. You only need to run this command once. 

In order to build the artifacts that encompass Redhawk Java Tools from source. Run the following command:

[IMPORTANT]
====
Maven 3.1.0+ is required for this build.
====
----
mvn clean install
----

== Build Docs 

Each individual project has it's own readme defining how to build it's docs. If you'd like to build the full user manual. Run this profile: 

----
mvn -P jaxb-generation,docs compile
----

== Build All Artifacts

To build the docs and demos you can run the following command: 

----
mvn -Djava.io.tmpdir=./ deploy -P docs,jaxb-generation,default
----

== Running Integration Tests

Currently the integration tests are run off a local install of REDHAWK. The domain is run locally and uses the following defaults:

* port: 2809
* domainName: REDHAWK_DEV

Once you have REDHAWK installed and a domain configured with the defaults listed above. You can run this command to get the integration tests to work:

	mvn -PlocalIT clean install 

This will be made more configurable in the future and will eventually also have an option to run off a docker image of REDHAWK. 


=== Trouble Shooting

If you run into this error building the docs

----
[ERROR] Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:1.5.3:process-asciidoc (output-pdf) on project redhawk-rest: Execution output-pdf of goal org.asciidoctor:asciidoctor-maven-plugin:1.5.3:process-asciidoc failed: org.jruby.exceptions.RaiseException: (NotImplementedError) fstat unimplemented unsupported or native support failed to load -> [Help 1]
----

You'll need to specify the java.io.tmpdir with your maven command. So your command will end up looking like this:

----
mvn -P -Djava.io.tmpdir=./ -P jaxb-generation,docs compile
----

== Copyright 

This work is protected by Copyright. Please refer to the link:COPYRIGHT[COPYRIGHT File] for more details.
