[#redhawk-driver-code-examples]
== `RedhawkDriver` Code Examples

The following code examples explain how to use the `RedhawkDriver` class. 

=== Get a REDHAWK Domain

[source,java,indent=0]
.`RedhawkDriverIT.java`
----
include::snippets/RedhawkDriverIT.java[lines=69]
----

=== Get a REDHAWK Device Manager  

[source,java,indent=0]
.`RedhawkDriverIT.java`
----
include::snippets/RedhawkDriverIT.java[lines=80..83]
----

=== Get a REDHAWK Device  

[source,java,indent=0]
.`RedhawkDriverIT.java`
----
include::snippets/RedhawkDriverIT.java[lines=93..97]
----

=== Get a REDHAWK Application 

[source,java,indent=0]
.`RedhawkDriverIT.java`
----
include::snippets/RedhawkDriverIT.java[lines=138]
----

=== Get a REDHAWK Component 

[source,java,indent=0]
.`RedhawkDriverIT.java`
----
include::snippets/RedhawkDriverIT.java[lines=143]
----

=== Get a REDHAWK Component's Port

[source,java,indent=0]
.`RedhawkDriverIT.java`
----
include::snippets/RedhawkDriverIT.java[lines=147]
----

=== Helper Utility Examples 

The `RedhawkDriver` includes helper utilities to enable users to easily access their REDHAWK Domain/REDHAWK Device Managers/REDHAWK Devices. These helper methods only work if there is only one REDHAWK Domain/REDHAWK Device Manager/REDHAWK Device available. If more than one REDHAWK Domain/REDHAWK Device Manager/REDHAWK Device exists, use the methods provided in <<Get a REDHAWK Domain>>, <<Get a REDHAWK Device Manager>>, or <<Get a REDHAWK Device>> to access those resources. 

[source,java,indent=0]
.`RedhawkDriverIT.java`
----
include::snippets/RedhawkDriverIT.java[lines=103..108]
----

