== `RedhawkEventChannel` Code Examples

Below are code examples for using the `RedhawkEventChannel` interface. 

=== Create an Event Channel Listener 

The Redhawk Driver has abstract classes that provide base functionality for the different event types provided in REDHAWK. Users can extend one of the Helper abstract classes like shown below and would only be responsible for implementing the onMessage function.

[source,java,indent=0]
.`RedhawkEventChannelIT.java`
----
include::snippets/RedhawkEventChannelIT.java[lines=136..150]
----

=== Subscribe and Unsubscribe to an Event Channel

Using the Listener defined above below are examples of subscribing and unsubscribing to an Event Channel. 

[source,java,indent=0]
.`RedhawkEventChannelIT.java`
----
include::snippets/RedhawkEventChannelIT.java[lines=100..105]
----

Unsubscribe by using the following code: 

[source,java,indent=0]
.`RedhawkEventChannelIT.java`
----
include::snippets/RedhawkEventChannelIT.java[lines=115]
----

=== Interacting with Event Channel Registrants

Every time a user subscribes or produces data to an Event Channel a Registrant is created. You can see that list of registrants and unsubscribe particular registrants using the code below. 

[source,java,indent=0]
.`RedhawkEventChannelIT.java`
----
include::snippets/RedhawkEventChannelIT.java[lines=66..70]
----

[source,java,indent=0]
.`RedhawkEventChannelIT.java`
----
include::snippets/RedhawkEventChannelIT.java[lines=84..85]
----