export const domainConfigs = state => state.domainConfigs
export const launchedWaveforms = state => state.launchedWaveforms
export const configToEdit = state => state.configToEdit
export const availableWaveforms = state => state.availableWaveforms
export const waveformComponents = state => state.waveformComponents
export const componentPorts = state => state.componentPorts
export const componentPropertiesToEdit = state => state.componentPropertiesToEdit
export const propComponentName = state => state.propComponentName
export const showWaveformController = state => state.showWaveformController
export const waveformToControl = state => state.waveformToControl
export const baseURI = state => state.baseURI
export const showLaunchWaveformModal = state => state.showLaunchWaveformModal
export const waveformToLaunch = state => state.waveformToLaunch
export const showDomain = state => state.showDomain
export const wsURL = state => state.wsURL
export const showEditDomainConfig = state => state.showEditDomainConfig
export const configToView = state => state.configToView
export const showWaveformComponents = state => state.showWaveformComponents
