export const available = state => state.available
export const nameServer = state => state.nameServer
export const domainName = state => state.domainName
export const baseURL = state => state.baseURL
export const appMetrics = state => state.appMetrics
export const appMetricsURL = state => state.appMetricsURL
export const appMetricsKeys = state => state.appMetricsKeys
export const appMetricsToView = state => state.appMetricsToView
export const appMetricsType = state => state.appMetricsType
