== Getting Started

After installing REDHAWK Enterprise Integration, the following directories are displayed:

* `karaf-${karaf.version}`: Directory contains a custom distribution of Karaf prepackaged with all REDHAWK Java Tool assets. 
* `shell`: Programatic access to REDHAWK Driver via the shell. 
* `jacorb-deps`: All dependencies needed to configure REDHAWK Driver to use JacORB instead of the default ORB provided by Java.

=== Working with Karaf

. To start Karaf, in the bin directory for Karaf, run the start script:
+
----
 ./start
----

. To access the Karaf console, in the bin directory for Karaf, run the client script:
+
----
 ./client
----

. Once logged in, run the command 'list' to display the REDHAWK Assets that have been preinstalled. Each asset includes documentation. Refer to the appropriate section in the online documentation for information about interacting with the individual assets. For more details on Karaf, refer to  https://karaf.apache.org/manual/latest/[Apache Karaf documentation]. 

. Begin using the bundles provided to interact with REDHAWK or write your own applications that leverage the REDHAWK Enterprise Integration bundles to interact with REDHAWK.

=== Configuring JacORB w/ Karaf

In order to make the REDHAWK Driver running inside of Karaf use JacORB instead of Sun ORB you'll need to add the following properties to your system.properties file:

----
	org.omg.CORBA.ORBSingletonClass=org.jacorb.orb.ORBSingleton
	org.omg.PortableInterceptor.ORBInitializerClass.standard_init=org.jacorb.orb.standardInterceptors.IORInterceptorInitializer
	org.omg.CORBA.ORBClass=org.jacorb.orb.ORB
----

In order to add specific configuration for your ORB you'll need to also add 

