== Getting Started

After installing REDHAWK Enterprise Integration, the following directories are displayed:

* `karaf-${karaf.version}`: Directory contains a custom distribution of Karaf prepackaged with all REDHAWK Java Tool assets. 
* `shell`: Programatic access to REDHAWK Driver via the shell. 
* `jacorb-deps`: All dependencies needed to configure REDHAWK Driver to use JacORB instead of the default ORB provided by Java.

=== Working with the Shell

The shell provides a convenient method to use the REDHAWK Driver without an IDE or other development tools. To start the REDHAWK Driver shell environment:

. Run the jrepl script:
+
----
 ./jrepl
----
In the console, you have access to the necessary imports for REDHAWK Driver via 
 `:eval driver-imports`. You also have access to all the classes in REDHAWK Driver. 

==== Example Commands

* To create an Application: 

 driver = new RedhawkDriver(); 
 application = driver.getDomain("REDHAWK_DEV").createApplication("MyFirstApplication", "/waveforms/rh/FM_mono_demo/FM_mono_demo.sad.xml")
	
* To start an Application: 

 application.start();

* To release an Application:
	
 application.release();

More example commands can be found in the <<redhawk-driver-code-examples>> section.

=== Working with Karaf

. To start Karaf, in the bin directory for Karaf, run the start script:
+
----
 ./start
----

. To access the Karaf console, in the bin directory for Karaf, run the client script:
+
----
 ./client
----

. Once logged in, run the command 'list' to display the REDHAWK Assets that have been preinstalled. Each asset includes documentation. Refer to the appropriate section in the online documentation for information about interacting with the individual assets. For more details on Karaf, refer to  https://karaf.apache.org/manual/latest/[Apache Karaf documentation]. 

. Begin using the Java Tools provided to interact with REDHAWK or write your own applications that leverage these tools to interact with REDHAWK.


