== Installing REDHAWK Enterprise Integration

=== Installing via Tarball

. Navigate to the directory where you want to install REDHAWK Enterprise Integration, and untar the tarball:
+
----
tar -xzf ${project.parent.artifactId}.gz
----
+

. If not already set in your `.bashrc/.bash_profile`, set the `JAVA_HOME` environment variable by adding the following:
+
----
JAVA_HOME=[path to java 8]
export JAVA_HOME
----
+

. Source your `.bashrc/.bash_profile`:
+
----
. ~/.bashrc or ~/.bash_profile
----


=== Installing via RPM

IMPORTANT: If installing via RPM, you must be root or have sudo privileges.

. Run this command to install the RPMs:
+
----
 yum install ${project.parent.artifactId}-*-${project.version}-noach.rpm
----
+

By default, the RPMs  are installed in `/usr/local/redhawk`. If you resolved the dependency during install, the RPM installs jre-1.8 for you.
+

. If you did not resolve the dependency during install, add a `JAVA_HOME` environment variable for Karaf to run properly (refer to the previous procedure, Installing via Tarball).
