== Installing REDHAWK Enterprise Integration

=== Installing via Tarball

. Navigate to the directory where you want to install REDHAWK Enterprise Integration, and untar the tarball:
+
----
tar -xzf ${project.parent.artifactId}.gz
----
+

. If not already set in your `.bashrc/.bash_profile`, set the `JAVA_HOME` environment variable by adding the following:
+
----
JAVA_HOME=[path to java 8]
export JAVA_HOME
----
+

. Source your `.bashrc/.bash_profile`:
+
----
. ~/.bashrc or ~/.bash_profile
----


=== Installing via RPM

. Run this command to install the RPM:
+
----
 rpm -i ${project.parent.artifactId}-dist-${project.version}-noach.rpm
----
+

By default, the RPM  is installed in `/usr/local/redhawk`.
If you decided to resolve the dependency during install, the RPM installs jre-1.8 for you. Add a `JAVA_HOME`(see step 2 in tarball instructions) environment variable for Karaf to run properly.

If using the RPM users will need to root or have sudo priviledges to perform tasks like starting KARAF or interacting with the java shell provided. 
