== Introduction 

REDHAWK Java Tools is a suite of software written in Java for interacting with a REDHAWK Domain. The suite includes:

* Redhawk Driver: Provides simplified access to REDHAWK via standard Java interfaces. The goal is to shield all interaction with the underlying REDHAWK Components as well as provide a simplified API for Java developers interacting with a REDHAWK Domain. The driver can be leveraged as a standalone jar file.  
* Redhawk Connector: Implements OSGi's Managed Service Factory interface to allow users to register pre-configured instances of REDHAWK connections into a Karaf container. 
* Redhawk Rest: Provides REST Service to command and control a REDHAWK instance.
* Redhawk Websocket: Provides an HTML5-compliant Websocket implementation that enables the ability to stream data from any Redhawk BulkIO enabled Port or Event Channel. 
* Camel Redhawk: Provides a Camel Component for interacting with a REDHAWK Domain. You can connect this Component with other Apache Camel Components as a data flow solution.

The suite of software is prepackaged in a custom Karaf distribution to help users easily get started using REDHAWK Java Tools. 




