== Introduction 

REDHAWK Enterprise Integration is a suite of software for interacting with a REDHAWK Domain in the Java Runtime Environment. The suite includes:

* <<REDHAWK Driver>>: Provides simplified access to REDHAWK via standard Java interfaces. The goal is to shield all interaction with the underlying REDHAWK Components as well as provide a simplified API for Java developers interacting with a REDHAWK Domain. The driver can be leveraged as a standalone Java ARchive (JAR) file.  
* <<REDHAWK Connector>>: Implements OSGi's Managed Service Factory interface to allow users to register pre-configured instances of REDHAWK connections into a Karaf container. 
* <<REDHAWK REST>>: Provides REST Service to command and control a REDHAWK instance.
* <<REDHAWK WebSocket>>: Provides an HTML5-compliant Websocket implementation that enables the ability to stream data from any REDHAWK BulkIO-enabled Port or Event Channel. 
* <<REDHAWK Camel Component>>: Provides a Camel Component for interacting with a REDHAWK Domain. This Component can be connected with other Apache Camel Components as a data flow solution.

The suite of software is prepackaged in a custom Karaf distribution to help users easily get started using REDHAWK Enterprise Integration. 




