=== Web Server Configuration

The web endpoints <<REDHAWK REST>> and websocket endpoints <<REDHAWK WebSocket>> are all hosted by a http://www.eclipse.org/jetty/documentation/[Jetty] server running inside of your Karaf container. Karaf uses https://ops4j1.jira.com/wiki/display/paxweb/Pax+Web[Pax Web] to manage your Jetty instance in an OSGi environment. 

==== Pax Web Config

The `org.ops4j.pax.web.cfg` has the parameters necessary for Pax to configure your Jetty server in the OSGi(Karaf in our case) environment. One of the benefits of using Pax Web to manage your Jetty instance is it enables you to update Pax Web configuration and the change take place without needing to restart your Karaf. SSL is setup by default through Pax Web. See the https://ops4j1.jira.com/wiki/display/paxweb/SSL+Configuration[SSL Configuration] section of Pax Web documentation for more details.

===== Certificates

The keystore and truststore information is contained in the `systems.properties` and we're using standard javax.net.ssl.* properties for setting them. This allows any other bundles that may need keystore or truststore information to retrive it in one place. 

* `javax.net.ssl.keyStore`: Path to your key store
* `javax.net.ssl.keyStorePassword`: Password for your key store
* `javax.net.ssl.keyStoreType`: Type for your key store. 
* `javax.net.ssl.trustStore`: Path to your trust store
* `javax.net.ssl.trustStorePassword`: Password for your trust store
* `javax.net.ssl.trustStoreType`: Type for your trust store

===== Update HTTP Port

If you'd like to change your http port update the `org.osgi.service.http.port` property. By default this is 8181.

===== Update HTTPS Port

If you'd like to change your https port update the `org.osgi.service.http.port.secure` property. By default this is 8182. 

===== Disable HTTP

If you'd like to disable http update the `org.osgi.service.http.enabled` to be false instead of true.

===== Disable HTTPS

If you'd like to disable https update the `org.osgi.service.http.secure.enabled` to be false instead of true.

===== Cipher Suites and other Security Configs

There are a plethora of Cipher Suites you can enable and disable via your org.ops4j.pax.web.cfg/Jetty.xml file. The ciphers that are available to you is dependent on which JRE/JDK you're using, browser type/version and the security posture applicable to your situation. Since this varies so much we have not included/excluded any cipher suites in the default configuration. 

* `org.ops4j.pax.web.ssl.ciphersuites.included`: Included SSL/TLS Cipher Suites Regex
* `org.ops4j.pax.web.ssl.ciphersuites.excluded`: Excluded SSL/TLS Cipher Suites Regex
* `org.ops4j.pax.web.ssl.protocols.included`: Included SSL/TLS Protocols
* `org.ops4j.pax.web.ssl.protocols.excluded`: Excluded SSL/TLS Protocols
* `org.ops4j.pax.web.ssl.renegotiationAllowed`: SSL Renegotiation allowed, is defaulted to true. 

Additional Info:

* http://docs.oracle.com/javase/8/docs/technotes/guides/security/jsse/JSSERefGuide.html#InstallationAndCustomization[Customizing JSSE]
* https://typesafehub.github.io/ssl-config/CipherSuites.html[More Cipher Details]
* JDK/JRE security properties file is located in ${JAVA_HOME}/lib/security/java.security .

===== Logging

Pax Web logs have been preconfigured to go into ${karaf.data}/pax-web/pax-web.log file. You can find the log configuration in `org.ops4j.pax.logging.cfg`. If you need to see additional logs update the logger `log4j.logger.org.eclipse.pax.web` to your desired state. 

===== Additional Pax Web Information

In order to configure additional Jetty configuration like login modules, connectors, etc... you'll need to use an external jetty.xml file. This property is set via:

* org.ops4j.pax.web.config.file: by default this file is in ${karaf.base}/etc/jetty.xml . 

Refer to https://ops4j1.jira.com/wiki/spaces/paxweb/pages/12059279/Advanced+Jetty+Configuration[Advanced Jetty Configuration] section for details. 

==== Jetty config

Jetty configuration can be found in ${karaf.base}/etc/jetty.xml. The jetty configuration sets up the login modules for your HTTP server. For more details on Jetty and JAAS support refer to the http://www.eclipse.org/jetty/documentation/9.4.x/jaas-support.html[JAAS Support] section of the Jetty docs. You can skip straight to the http://www.eclipse.org/jetty/documentation/9.4.x/jaas-support.html#_a_closer_look_at_jaasloginservice[JAASLoginService] section for information on the Login Service preconfigured in your container.

The SSL/TLS params can be configured via the `org.ops4j.pax.web.cfg` as discussed above. If you'd like you can instead do all this configuration via the Jetty.xml. Refer to the https://www.eclipse.org/jetty/documentation/9.4.6.v20170531/configuring-ssl.html[Configuring SSL/TLS] section of the Jetty docs for more details.

===== SSL Configuration via Jetty

If you'd like to do your SSL Configuration via Jetty instead here's a snippet you can add to the jetty.xml for a minimum ssl/tls configuration. 

[source,xml]
-----
<!-- =========================================================== -->
	<!-- SSL Configuration below -->
	<!-- Set up sslContext Factory with standard javax properties -->
	<!-- Latest docs: https://www.eclipse.org/jetty/documentation/9.4.x/configuring-ssl.html, remember to 
		use docs relevant to jetty available in your karaf instance
	 -->
	<New id="sslContextFactory" class="org.eclipse.jetty.util.ssl.SslContextFactory">
		<Set name="KeyStorePath"><SystemProperty name="javax.net.ssl.keyStore" /></Set>
		<Set name="KeyStorePassword"><SystemProperty name="javax.net.ssl.keyStorePassword" /></Set>
		<Set name="KeyManagerPassword"><SystemProperty name="javax.net.ssl.keyStorePassword" /></Set>
		<Set name="TrustStorePath"><SystemProperty name="javax.net.ssl.keyStore" /></Set>
		<Set name="TrustStorePassword"><SystemProperty name="javax.net.ssl.keyStorePassword" /></Set>
		<Set name="renegotiationAllowed">FALSE</Set>		
	</New>
	
	<New id="httpsConnector" class="org.eclipse.jetty.server.ServerConnector">
		<Arg name="server"><Ref refid="Server"/></Arg>
		<Arg name="factories">
			<Array type="org.eclipse.jetty.server.ConnectionFactory">
              <Item>
                <New class="org.eclipse.jetty.server.SslConnectionFactory">
                  <Arg name="next">http/1.1</Arg>
                  <Arg name="sslContextFactory"><Ref refid="sslContextFactory"/></Arg>
                </New>
              </Item>
              <Item>
                <New class="org.eclipse.jetty.server.HttpConnectionFactory">
                  <Arg name="config"><Ref refid="httpConfig"/></Arg>
                </New>
              </Item>
       		</Array>		
		</Arg>
		<Set name="name">redhawkHTTPS</Set>
	</New>
	
	<Call name="addConnector">
		<Arg>
			<Ref refid="httpsConnector"/>
		</Arg>
	</Call>
-----

===== Cipher Suites

Refer to the https://www.eclipse.org/jetty/documentation/9.4.6.v20170531/configuring-ssl.html#configuring-sslcontextfactory-cipherSuites[Disabling/Endabling Specific Cipher Suites] section of the Jetty documentation for pointers on how to add/exclude ciphers. 

===== Password Obfuscation

By default the passwords are stored in plain text. If you'd like to obfuscate the passwords jetty provides utilities for that. Refer to the http://www.eclipse.org/jetty/documentation/9.4.x/configuring-security-secure-passwords.html[Secure Password Obfuscation] section from Jetty for more details. The jar necessary for generating the obsfucated password can be found in ${karaf.base}/system/org/eclipse/jetty/jetty-util/{jetty.version}/jetty-util-{jetty.version}.jar . 

===== Logging

Jetty logs have been preconfigured to go into ${karaf.data}/jetty/jetty.log file. You can find the log configuration in `org.ops4j.pax.logging.cfg`. If you need to see additional logs update the logger `log4j.logger.org.eclipse.jetty` to your desired state.

*Note: Jetty has many versions so be sure to check the documentation for the version of Jetty that is in your Karaf container* 