= REDHAWK Camel Component 

The REDHAWK Camel Component provides a convenient method to integrate REDHAWK Domain functionality in a Camel Context. http://camel.apache.org/[Apache Camel] is a tool for solving any routing (data flow) or mediation problems within your system. Using Apache Camel provides access to 100+ http://camel.apache.org/components.html[Components] to solve routing/mediation problems. If your system needs to persist data from an Event Channel, rather than writing more code, you can reuse the components already provided by Camel to store your data in NoSQL/SQL data stores. If your system needs to send data from the REDHAWK Corba File System to a JMS solution for distribution, rather than writing more code, you can integrate with one of the Camel Components for JMS. The numerous available components provide endless possibilities.

== REDHAWK Data Endpoint

Enables direct interaction between REDHAWK Component Ports and your Apache Camel Context. 

=== URI Format 

----
redhawk://data:<nameserver host>:<nameserver port>:<domain name>?waveformName=<waveform name>&componentName=<component name>&portName=<port name>&portType=<port type>
----

=== Endpoint Options

Enables direct interaction between a REDHAWK Corba FileSystem and your Apache Camel Context.

The REDHAWK Data endpoint options are described in the following table.

|===

|Name | Default Value | Description

| bufferSize
| 2000
| Size of buffer for holding queued packets waiting to be processed. 

| decimateTo
| -1
| Sample size to take from the packets.

|===

////
TODO: Come up with nice example route
=== Sample Route

////

== REDHAWK File Endpoint

Enables direct interaction between a REDHAWK Event Channel and your Apache Camel Context. 

=== URI Format

----
redhawk://file-manager:<nameserver host>:<nameserver port>:<domain name>?directory=<directory on FS>
----

=== Endpoint Options

Enables direct interaction between a REDHAWK Corba FileSystem and your Apache Camel Context.

The REDHAWK File endpoint options are described in the following table.


|===

| Name | Default Value | Description

| fileManagerType
| domain
| Location of the root of Corba FileSystem. If `domain`, then root is `$SDROOT/dom` . If `dev`, then root is root of the Device Manager you set. 

| deviceManagerName
| n/a
| Name of the Device Manager. Only used if the `fileManagerType` is `device`.

|===

////

=== Sample Route

TODO: Come up with nice example route
=== Sample Route

////

== REDHAWK Event Channel Endpoint

=== URI Format

----
redhawk://event-channel:<nameserver host>:<nameserver port>:<domain name>?eventChannelName=<event channel name>&dataTypeName=<type of message>
----

=== Endpoint Options

Enables direct interaction between a REDHAWK Corba FileSystem and your Apache Camel Context.

The REDHAWK Event Channel endpoint options are described in the following table.

|===

| Name | Default Value | Description

| eventChannelName
| n/a
| Name of the event channel to be used.

| dataTypeName
| n/a
| Type of message for which to listen. Options are `messages`, `properties`, `logEvent`, `propertyChanges`.

|===
