= REDHAWK Camel Component 

The REDHAWK Camel Component gives users an easy way to integrate REDHAWK Domain functionality in a Camel Context. http://camel.apache.org/[Apache Camel] is a tool for solving any routing(data flow) or mediation problems your system may have. Just by using Apache Camel you get access to 100+ http://camel.apache.org/components.html[Components] to solve your routing/mediation problems. If your system needs to persist data from an Event Channel no need to write more code reuse the components already provided by camel to store your data in NoSQL/SQL data stores. If your system needs to send data from the REDHAWK Corba File System to a JMS solution for distribution no need to write more code just integrate with one of the Camel Components for JMS. With so many different components available to you the possibilities are endless.

== REDHAWK Data Endpoint

Enables direct interaction between a REDHAWK Component ports and your Apache Camel Context. 

=== URI Format 

----
redhawk://data:<nameserver host>:<nameserver port>:<domain name>?waveformName=<waveform name>&componentName=<component name>&portName=<port name>&portType=<port type>
----

=== Endpoint Options

Enables direct interaction between a REDHAWK Corba FileSystem and your Apache Camel Context.

The REDHAWK Data endpoint has the following options for the options

|===

|Name | Default Value | Description

| bufferSize
| 2000
| Size of buffer for holding queued packets waiting to get processed. 

| decimateTo
| -1
| Sample size to take from the packets

|===

////
TODO: Come up with nice example route
=== Sample Route

////

== REDHAWK File Endpoint

Enables direct interaction between a REDHAWK Event Channel and your Apache Camel Context. 

=== URI Format

----
redhawk://file-manager:<nameserver host>:<nameserver port>:<domain name>?directory=<directory on FS>
----

|===

| Name | Default Value | Description

| fileManagerType
| domain
| Where the Root of Corba FileSystem is. If 'domain' then root with be $SDROOT/dom . If 'dev' then root will be root of the device manager you set. 

| deviceManagerName
| n/a
| The name of the device manager. Only used if the fileManagerType is 'device'

|===

=== Sample Route

////

TODO: Come up with nice example route
=== Sample Route

////

== REDHAWK Event Channel Endpoint

=== URI Format

----
redhawk://event-channel:<nameserver host>:<nameserver port>:<domain name>?eventChannelName=<event channel name>&dataTypeName=<type of message>
----

|===

| Name | Default Value | Description

| eventChannelName
| n/a
| The name of the event channel to use

| dataTypeName
| n/a
| Type of message to listen for. Options are messages, properties, logEvent, propertyChanges

|===