= Redhawk Websocket

== Documentation

To generate the documentation for this project run the following command:

 mvn -P docs generate-resources

This generates documentation for you at this location 'redhawk-rest/target/docs/' . In that location is a pdf and html file with the documentation generated for this project.

=== Trouble Shooting

If you run into this error building the docs

----
[ERROR] Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:1.5.3:process-asciidoc (output-pdf) on project redhawk-rest: Execution output-pdf of goal org.asciidoctor:asciidoctor-maven-plugin:1.5.3:process-asciidoc failed: org.jruby.exceptions.RaiseException: (NotImplementedError) fstat unimplemented unsupported or native support failed to load -> [Help 1]
----

You'll need to specify the java.io.tmpdir with your maven command. So your command will end up looking like this:

----
mvn -P -Djava.io.tmpdir=./ docs generate-resources
----

////
To install into karaf base run the following commands:

	feature:repo-add mvn:redhawk/redhawk-feature/2.0.1.U2-SNAPSHOT/xml/features
	feature:install redbus-redhawk-websocket
	
This feature install the redhawk websocket into karaf base. 

TODO: Write an example of how to use it 
////