# RPM package for SimulatorNode
# This file is regularly AUTO-GENERATED by the IDE. DO NOT MODIFY.

# By default, the RPM will install to the standard REDHAWK SDR root location (/var/redhawk/sdr)
# You can override this at install time using --prefix /new/sdr/root when invoking rpm (preferred method, if you must)
%{!?_sdrroot: %global _sdrroot /var/redhawk/sdr}
%define _prefix %{_sdrroot}
Prefix: %{_prefix}

Name: SimulatorNode
Summary: Node SimulatorNode
Version: 1.0.0
Release: 1
License: None
Group: REDHAWK/Nodes
Source: %{name}-%{version}.tar.gz
# Require the device manager whose SPD is referenced
Requires: DeviceManager
# Require each referenced device/service
Requires: rh.FmRdsSimulator
BuildArch: noarch
BuildRoot: %{_tmppath}/%{name}-%{version}

%description

%prep
%setup

%install
%__rm -rf $RPM_BUILD_ROOT
%__mkdir_p "$RPM_BUILD_ROOT%{_prefix}/dev/nodes/SimulatorNode"
%__install -m 644 DeviceManager.dcd.xml $RPM_BUILD_ROOT%{_prefix}/dev/nodes/SimulatorNode/DeviceManager.dcd.xml

%files
%defattr(-,redhawk,redhawk)
%dir %{_prefix}/dev/nodes/SimulatorNode
%{_prefix}/dev/nodes/SimulatorNode/DeviceManager.dcd.xml
