= REDHAWK Jaxrs Security Filter

The REDHAWK Jaxrs Security filter provides the ability to dynamically assign role-based permissions to REDHAWK REST and WebSocket endpoints. 
For example, this feature may be used to limit the ability to create and release Waveforms to include only users with an administrative role.

Currently, this feature is only supported by the Jetty Distribution of REDHAWK Enterprise Integration and disabled by default. To enable the REDHAWK Jaxrs Security filter feature, use the following procedure:

. In `${jetty.home}/webapps`, locate the `redhawk-rest.xml` file, and in this file, locate the section that is currently commented out. 

. Remove the comment markings for `overrideDescriptor` and `jaxrsperms`. 
+
The following listing displays the modified `redhawk-rest-xml` file.
+
[source,xml]
----
  <Set name="overrideDescriptor"><Property name="jetty.home" default="." />/etc/rest_jaas_override-web.xml</Set>

	<!--
		JAAS Login Service:
			Uncomment XML below to enable JAAS Authentication
	 -->
  	<Set name="securityHandler">
    	<New class="org.eclipse.jetty.security.ConstraintSecurityHandler">
     		<Set name="loginService">
       			<New class="org.eclipse.jetty.jaas.JAASLoginService">
         			<Set name="name">REDHAWK_JAAS_REALM</Set>
         			<Set name="loginModuleName">xyz</Set>
       			</New>
     		</Set>
    	</New>
  	</Set>

  	<!--
		Use JNDI to set location of the REST permissions file
	 -->
	<New id="jaxrsperms" class="org.eclipse.jetty.plus.jndi.EnvEntry">
  		<Arg>redhawk.jaxrs.permissions.file</Arg>
  		<Arg type="java.lang.String"><Property name="jetty.home" default="." />/etc/redhawk.jaxrs.permissions.csv</Arg>
  		<Arg type="boolean">true</Arg>
	</New>
----
+
The REDHAWK REST endpoints are now using the Java Authentication and Authorization Service.

. To enable the REDHAWK Jaxrs Security filter feature for REDHAWK Websocket, in `${jetty.home}/webapps`, locate the `redhawk-websocket.xml` file, and in this file, locate the section that is currently commented out. Remove the comment markings for `overrideDescriptor` and `jaxrsperms`.
+
The REDHAWK Websocket endpoints are now using the Java Authentication and Authorization Service.

. To access the endpoints, you must login. All the Security configuration for REDHAWK REST is provided via an overrides file referenced in the configuration above at `${jetty.home}/etc/rest_jaas_override-web.xml`. For login information, refer to `${jetty.home}/etc/login.properties`. Login configuration can
be found at `${jetty.home}/etc/login.conf`. For more information on security with Jetty, refer to the *Configuring Security* section of https://www.eclipse.org/jetty/documentation/[Jetty's Official Documentation].

. By default, users in the `guest` and `admin` roles have permissions set for any endpoints on the REDHAWK REST and WebSocket endpoints. To change the permissions for endpoints, update the `redhawk.jaxrs.permissions.csv` file
located in `${jetty.home}/etc`. Edit the permissions to suit your use case. `Path` and `Role(s)` are required fields. The `Method` field is optional. 
The following listing displays example permissions:
+
----
#PATH, METHOD, Role(s)
/rest/redhawk.*,GET,"guest,admin"
/rest/redhawk.*,"POST,PUT,DELETE",admin
/ws/redhawk.*,,"guest,admin"
----


